### ISSUE TITLE
Ignore links to parent directories

### ISSUE THREAD

**Issue by Havvy** [Michael-F-Bryan/mdbook-linkcheck#1]
Links that traverse to the directory above the current directory should be ignored.

**Comment by Michael-F-Bryan** [comment]
I wasn't too sure how to deal with this one. I know *The Book* contains a bunch of links which go outside the current directory (e.g. `../../std/fs/struct.File.html`), but that doesn't actually point to anything until its deployed to the S3 bucket... 

Should we just ignore relative links which go outside of the book directory? I feel like it wouldn't be a good link checker if we silently ignored possibly broken links.

**Comment by ehuss** [comment]
What if you specified the deployment URL (for example https://doc.rust-lang.org/book/second-edition/ for the Rust Book), and any relative links that go outside the current directory would be verified by combining with that URL?

**Comment by Havvy** [comment]
Or at least a boolean flag for ignoring them...
