### ISSUE TITLE
Document how to integrate mdbook-linkcheck with GitLab CI / Travis CI

### ISSUE THREAD

**Issue by ngirard** [Michael-F-Bryan/mdbook-linkcheck#14]
Such information is currently sparse and difficult to find. It would be useful if mdbook-linkcheck's documentation would provide it.

**Comment by Michael-F-Bryan** [comment]
I don't think there's anything special you need to do if you're [already running `mdbook` as part of your CI](https://rust-lang-nursery.github.io/mdBook/continuous-integration.html). 

You just need to run `cargo install mdbook-linkcheck` when installing `mdbook` and the linkchecker will be run whenever `mdbook build` is executed. If `mdbook-linkcheck` fails that'll make the build error and your CI will go red.

**Comment by danieltrautmann** [comment]
I've created a Docker image that includes mdBook and mdbook-linkcheck, which doesn't include Rust to keep the size of the image low.

https://gitlab.com/danieltrautmann/docker-mdbook

Note that it is hosted by the GitLab registry.

**Comment by ngirard** [comment]
@danieltrautmann Great, thanks for your work!

**Comment by Michael-F-Bryan** [comment]
@danieltrautmann do you mind if I mention your docker image in the README?

**Comment by danieltrautmann** [comment]
@Michael-F-Bryan Not at all. It is meant to be used by others.
