### ISSUE TITLE
mdbook always destroys cache

### ISSUE THREAD

**Issue by mark-i-m** [Michael-F-Bryan/mdbook-linkcheck#17]
@Michael-F-Bryan It appears that when mdbook starts, it destroys `book/`, which includes `book/linkcheck/cache.json`. Running in standalone mode works though. Perhaps an easy fix would be to allow specifying an alternate cache location?

**Comment by Michael-F-Bryan** [comment]
This should be handled by https://github.com/rust-lang-nursery/mdBook/pull/985. It looks like the last `mdbook` release was 2 months ago though, so we can't take advantage of it yet.

Being able to specify an alternate cache directory through configuration doesn't hurt though.

**Comment by Michael-F-Bryan** [comment]
This is now fixed upstream in `v0.3.2` ([CHANGELOG entry](https://github.com/rust-lang-nursery/mdBook/blob/master/CHANGELOG.md#changed)).
