### ISSUE TITLE
Incomplete certificate chain

### ISSUE THREAD

**Issue by TjeuKayim** [Michael-F-Bryan/mdbook-linkcheck#19]
This link checker fails if the server's certificate chain is incomplete.
For example, https://incomplete-chain.badssl.com/ will throw: `error trying to connect: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:../ssl/statem/statem_clnt.c:1924: (unable to get local issuer certificate)`.
Most browsers still accept this (AIA fetching).

Can mdbook-linkcheck get an option to ignore HTTPS certificates with incomplete chain? Maybe only for a whitelist of configured domains.

**Comment by Michael-F-Bryan** [comment]
I guess we *could* use [`reqwest::ClientBuilder::danger_accept_invalid_certs()`][1] to globally disable certificate validation when creating the HTTP client... But if the server on the other side has invalid certs most browsers will refuse to display the page, which is a pretty good definition for "broken link".

Can't you add the server to the `exclude` section under `[output.linkcheck]`?
 
[1]: https://docs.rs/reqwest/0.10.0-alpha.1/reqwest/struct.ClientBuilder.html#method.danger_accept_invalid_certs

**Comment by Michael-F-Bryan** [comment]
I'm going to close this issue as *Wont-Fix*. If your website has bad certificates then I'd argue that it *is* broken, and should be reported as such.
