### ISSUE TITLE
follow-web-links broken?

### ISSUE THREAD

**Issue by Blisto91** [Michael-F-Bryan/mdbook-linkcheck#38]
Maybe i'm just stupid but does this setting not prevent checking website links?

```
[output.linkcheck]
follow-web-links = false
```
With it set to false it still complains about a broken link like this.
```
[Broken link] 

[Broken link]: https://www.notaworkingwebsite.com/
```

**Comment by benmoss** [comment]
Yes, I think this is right. You can enable debug logging by running it with `RUST_LOG=debug` and yeah I'm seeing it check web links without that config set or with it set to false.

**Comment by benmoss** [comment]
I looked into solving this, but not sure how @Michael-F-Bryan would want to tackle it. It seems to have just not been implemented.

We probably want to leverage the `category` code for determining if a link is a web URL or not, but that code is private to the linkcheck library. I was thinking we could just filter the links from mdbook-linkcheck to remove `Url` links, but we'd have to make the category a public API.

**Comment by wonderfulspam** [comment]
As far as I can tell, this used to work but the `follow-web-links` config option is not being checked anymore. It seems to have been removed in [this commit](https://github.com/Michael-F-Bryan/mdbook-linkcheck/commit/186b78338f7f276bd49d8f6edc18385e9b74ba8c#diff-79041bf8c438a90e409d3287e2d04d87dd96440d14e14ce130cf442b419b884aL110). @Michael-F-Bryan is this a case of over-eager code deletion or is it something you're looking to re-implement differently?

The last version that respects the web links setting is 0.5.1.

**Comment by Michael-F-Bryan** [comment]
@wonderfulspam I split the code for actually checking links into its own crate ([`linkcheck`](https://github.com/Michael-F-Bryan/linkcheck)) and it seems like I forgot to take `follow-web-links` into account when overriding [`Context::should_ignore()`][should_ignore].

[should_ignore]: https://github.com/Michael-F-Bryan/mdbook-linkcheck/blob/cfd06b75e26cf8588e6d680862a4d2ecf6f3a8de/src/context.rs#L36-L41

**Comment by wonderfulspam** [comment]
That makes sense. I'm happy to try my hand at a PR if you don't already have a fix in mind!
