### ISSUE TITLE
`cargo install mdbook-linkcheck` fails

### ISSUE THREAD

**Issue by wez** [Michael-F-Bryan/mdbook-linkcheck#53]
Feels like something is under-specified in some deps somewhere? This is breaking my CI workflow :-(

```
error[E0053]: method `client` has an incompatible type for trait
  --> /home/wez/.cargo/registry/src/github.com-1ecc6299db9ec823/mdbook-linkcheck-0.7.2/src/context.rs:28:5
   |
28 |     fn client(&self) -> &Client { &self.client }
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected struct `reqwest::async_impl::client::Client`, found struct `Client`
   |
   = note: expected fn pointer `fn(&context::Context<'a>) -> &reqwest::async_impl::client::Client`
              found fn pointer `fn(&context::Context<'a>) -> &Client`
   = note: perhaps two different versions of crate `reqwest` are being used?
```

**Comment by Michael-F-Bryan** [comment]
Oops. 

I recently did a patch release of the `linkcheck` crate (used by `mdbook-linkcheck`) and updated its dependencies (including `reqwest`). I'm guessing what's happened is that `linkcheck` exposes `reqwest`'s v0.11 `Client` in a trait method and `mdbook-linkcheck` tries to implement that method by returning a v0.9 `Client`.

**Comment by Michael-F-Bryan** [comment]
@wez I've yanked version 0.3.2 of `linkcheck` and re-released it as 0.4.0. Can you re-enable `mdbook-linkcheck` and confirm that `cargo install mdbook-linkcheck` doesn't have that issue?

**Comment by wez** [comment]
I've confirmed that this works locally again, thanks!
I should know in a few minutes if the CI is happy, but I don't anticipate problems.

**Comment by wez** [comment]
Thanks!
