### ISSUE TITLE
Backend not found when using pre-built install?

### ISSUE THREAD

**Issue by ppannuto** [Michael-F-Bryan/mdbook-linkcheck#59]
I'm trying to get linkcheck set up in a CI environment, so I'm using a pre-built version of linkcheck. It seems to install just fine, and it will run `mdbook-linkcheck --version` without issue, but then running `mdbook` will fail to find the backend?

Here's the relevant snippet of [the full build log](https://app.netlify.com/sites/tock-book/deploys/61297e7119b5f400070c0fe8#L186):

```
5:08:39 PM: mdbook-linkcheck --version
5:08:39 PM: mdbook-linkcheck 0.7.4
5:08:39 PM: mdbook build
5:08:39 PM: 2021-08-28 00:08:39 [INFO] (mdbook::book): Book building has started
5:08:39 PM: 2021-08-28 00:08:39 [INFO] (mdbook::book): Running the html backend
5:08:39 PM: 2021-08-28 00:08:39 [INFO] (mdbook::book): Running the linkcheck backend
5:08:39 PM: 2021-08-28 00:08:39 [INFO] (mdbook::renderer): Invoking the "linkcheck" renderer
5:08:39 PM: 2021-08-28 00:08:39 [ERROR] (mdbook::renderer): The command `mdbook-linkcheck` wasn't found, is the "linkcheck" backend installed? If you want to ignore this error when the "linkcheck" backend is not installed, set `optional = true` in the `[output.linkcheck]` section of the book.toml configuration file.
2021-08-28 00:08:39 [ERROR] (mdbook::utils): Error: Rendering failed
```

As well as the [actual commands being run](https://github.com/tock/book/pull/18/files#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52R43).

Is there anything additional that needs to be done to "install" linkcheck beyond ensuring that `mdbook-linkcheck` is in `PATH`?

**Comment by Michael-F-Bryan** [comment]
That's odd. It should be enough to add `mdbook-linkcheck` to your `$PATH`.

Does this work correctly when you test locally?

**Comment by ppannuto** [comment]
Aha! After more aggressive local testing, I realized this had been picking up the already installed version on my dev machine rather than what the CI tooling installed. Because the Makefile manipulated the PATH, I needed to change the actual build command to from `mdbook build` to `sh -c "mdbook build"` to force it to use the new PATH. That got things working. Sorry for the noise here.
